name: energi

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6
  - pandas
  #- pylint # dev
  #- ipykernel # dev
  - selenium
  - pendulum
  - pymssql
  - xlrd
  - pip:
    - https://github.com/hultsfred/hkfunctions/archive/master.zip

